// 2024타경36029 대구 달성군 다사읍 공장 샘플 데이터

export const SAMPLE_CASE = {
  case_number: '2024타경36029',
  court_name: '대구지방법원 서부지원',
  property_type: '공장',
  address: '대구 달성군 다사읍 서재리 935',
  appraisal_value: '141.87',
  minimum_price: '69.52',
  ai_estimated_value: '160.77',
  land_area: '5597',
  building_area: '1369.8',
  auction_count: '3',
  next_auction_date: '',
  property_composition: '단독' as const,
};

export const SAMPLE_RIGHTS = [
  {
    seq: 1,
    right_type: '근저당',
    right_holder: '대구은행(을5)',
    claim_amount: '65.52',
    principal: '54.6',
    max_claim_amount: '65.52',
    interest_rate: '15',
    classification: '선순위',
    registration_date: '2020-08-31',
    priority_rank: 1,
  },
  {
    seq: 2,
    right_type: '근저당',
    right_holder: '대구은행(을6)',
    claim_amount: '16',
    principal: '13.33',
    max_claim_amount: '16',
    interest_rate: '15',
    classification: '매입채권(NPL)',
    registration_date: '2020-08-31',
    priority_rank: 2,
  },
  {
    seq: 3,
    right_type: '근저당',
    right_holder: '대구은행(을7)',
    claim_amount: '9.8',
    principal: '8.16',
    max_claim_amount: '9.8',
    interest_rate: '15',
    classification: '후순위',
    registration_date: '2020-08-31',
    priority_rank: 3,
  },
  {
    seq: 4,
    right_type: '근저당',
    right_holder: '일신종합(을8)',
    claim_amount: '5.4',
    principal: '4.5',
    max_claim_amount: '5.4',
    interest_rate: '15',
    classification: '후순위',
    registration_date: '2024-04-29',
    priority_rank: 4,
  },
];

export const SAMPLE_TENANTS = [
  {
    tenant_name: '김수진',
    move_in_date: '2011-12-07',
    deposit: '2000',
    monthly_rent: '165',
    has_opposition_right: true,
  },
  {
    tenant_name: '김정숙',
    move_in_date: '2021-05-11',
    deposit: '0',
    monthly_rent: '0',
    has_opposition_right: false,
  },
];

export const SAMPLE_ASSUMPTIONS = {
  auctionCostRate: '0.5',
  propertyTax: '0',
  smallTenantAmount: '2000',
  wageClaim: '0',
  investmentPeriodMonths: '12',
  bondDiscountBase: '15',
  holdingPeriodYears: '5',
  rentUnitPrice: '6000',
  vacancyRate: '20',
  opexRate: '15',
  pledgeLoanLtv: '75',
  pledgeLoanRate: '6.5',
  acquisitionTaxRate: '4.6',
  annualAppreciation: '2',
  exitCapRate: '5',
  evictionCost: '3000',
  repairCost: '5000',
  otherCostRate: '0.5',
  transferCostRate: '0.48',
  vehicleFeeRate: '1',
};
