// ─────────────────────────────────────────────────────────
//  Centralized Sample Listings – 100개 NPL 매물 데이터
// ─────────────────────────────────────────────────────────

export interface SampleListing {
  id: string
  seller_id: string
  institution: string
  title: string
  listing_type: string
  collateral_type: string
  address: string
  principal_amount: number
  appraised_value: number
  ltv_ratio: number
  risk_grade: 'A' | 'B' | 'C' | 'D' | 'E'
  status: 'ACTIVE' | 'PENDING' | 'CLOSED' | 'EXPIRED'
  visibility: 'PUBLIC' | 'MEMBERS' | 'VIP'
  description: string
  deadline: string
  delinquency_months: number
  area_sqm: number
  debtor_count: number
  created_at: string
  images?: string[]
}

// 가격 단위: 원
const 억 = 100_000_000

export const SAMPLE_LISTINGS: SampleListing[] = [
  // ── 아파트 10건 ─────────────────────────────────────────
  { id: 'lst-a01', seller_id: 'user-s1', institution: 'KB국민은행', title: '강남구 압구정동 현대아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '서울 강남구 압구정로 234', principal_amount: 18 * 억, appraised_value: 28 * 억, ltv_ratio: 64.3, risk_grade: 'A', status: 'ACTIVE', visibility: 'PUBLIC', description: '압구정 현대아파트 전용 84㎡. 재건축 추진 중. 선순위 없음.', deadline: '2026-04-30', delinquency_months: 8, area_sqm: 84, debtor_count: 1, created_at: '2026-02-15', images: ['https://picsum.photos/seed/apt-gangnam/800/500', 'https://picsum.photos/seed/apt-gangnam2/800/500', 'https://picsum.photos/seed/apt-gangnam3/800/500'] },
  { id: 'lst-a02', seller_id: 'user-s2', institution: '신한은행', title: '송파구 잠실동 엘스 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '서울 송파구 올림픽로 300', principal_amount: 12 * 억, appraised_value: 22 * 억, ltv_ratio: 54.5, risk_grade: 'A', status: 'ACTIVE', visibility: 'PUBLIC', description: '잠실엘스 전용 59㎡. 지하철 2호선 도보 5분.', deadline: '2026-05-15', delinquency_months: 6, area_sqm: 59, debtor_count: 1, created_at: '2026-02-20', images: ['https://picsum.photos/seed/apt-jamsil/800/500', 'https://picsum.photos/seed/apt-jamsil2/800/500'] },
  { id: 'lst-a03', seller_id: 'user-s3', institution: '하나은행', title: '서초구 반포동 아크로리버파크 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '서울 서초구 신반포로 270', principal_amount: 25 * 억, appraised_value: 45 * 억, ltv_ratio: 55.6, risk_grade: 'A', status: 'ACTIVE', visibility: 'VIP', description: '반포 아크로리버파크 전용 112㎡. 한강 조망.', deadline: '2026-04-20', delinquency_months: 4, area_sqm: 112, debtor_count: 1, created_at: '2026-01-25', images: ['https://picsum.photos/seed/apt-banpo/800/500'] },
  { id: 'lst-a04', seller_id: 'user-s1', institution: 'KB국민은행', title: '마포구 아현동 마포래미안푸르지오 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '서울 마포구 마포대로 190', principal_amount: 7.5 * 억, appraised_value: 12 * 억, ltv_ratio: 62.5, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '마포래미안 전용 59㎡. 역세권. 임차인 있음(보증금 2억).', deadline: '2026-05-30', delinquency_months: 14, area_sqm: 59, debtor_count: 1, created_at: '2026-03-01' },
  { id: 'lst-a05', seller_id: 'user-s4', institution: '우리은행', title: '성남시 분당구 정자동 아이파크 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '경기 성남시 분당구 정자일로 188', principal_amount: 6 * 억, appraised_value: 9.5 * 억, ltv_ratio: 63.2, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '분당 정자동 아이파크 전용 84㎡.', deadline: '2026-06-15', delinquency_months: 10, area_sqm: 84, debtor_count: 1, created_at: '2026-03-05' },
  { id: 'lst-a06', seller_id: 'user-s2', institution: '신한은행', title: '용인시 수지구 죽전동 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '경기 용인시 수지구 죽전로 120', principal_amount: 4.2 * 억, appraised_value: 6.5 * 억, ltv_ratio: 64.6, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '죽전역 인근 아파트 전용 74㎡. 연체 1년.', deadline: '2026-05-20', delinquency_months: 12, area_sqm: 74, debtor_count: 1, created_at: '2026-02-10' },
  { id: 'lst-a07', seller_id: 'user-s3', institution: '하나은행', title: '노원구 상계동 주공아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '서울 노원구 동일로 1340', principal_amount: 2.8 * 억, appraised_value: 4.2 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '노원 상계주공 전용 49㎡. 재건축 기대.', deadline: '2026-07-01', delinquency_months: 24, area_sqm: 49, debtor_count: 2, created_at: '2026-01-15' },
  { id: 'lst-a08', seller_id: 'user-s1', institution: 'KB국민은행', title: '인천 연수구 송도동 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '인천 연수구 센트럴로 250', principal_amount: 5.5 * 억, appraised_value: 8 * 억, ltv_ratio: 68.8, risk_grade: 'B', status: 'PENDING', visibility: 'PUBLIC', description: '송도 센트럴파크 인근 전용 84㎡.', deadline: '2026-06-30', delinquency_months: 18, area_sqm: 84, debtor_count: 1, created_at: '2026-03-10' },
  { id: 'lst-a09', seller_id: 'user-s4', institution: '우리은행', title: '부산 해운대구 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '부산 해운대구 마린시티2로 50', principal_amount: 8 * 억, appraised_value: 14 * 억, ltv_ratio: 57.1, risk_grade: 'B', status: 'ACTIVE', visibility: 'MEMBERS', description: '해운대 마린시티 전용 101㎡. 오션뷰.', deadline: '2026-05-10', delinquency_months: 9, area_sqm: 101, debtor_count: 1, created_at: '2026-02-28' },
  { id: 'lst-a10', seller_id: 'user-s2', institution: '신한은행', title: '대전 유성구 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '대전 유성구 도안대로 380', principal_amount: 3.2 * 억, appraised_value: 5 * 억, ltv_ratio: 64.0, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '유성구 도안신도시 전용 84㎡.', deadline: '2026-06-20', delinquency_months: 11, area_sqm: 84, debtor_count: 1, created_at: '2026-03-08' },

  // ── 오피스 10건 ─────────────────────────────────────────
  { id: 'lst-o01', seller_id: 'user-s1', institution: 'KB국민은행', title: '강남구 역삼동 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '서울 강남구 테헤란로 415', principal_amount: 35 * 억, appraised_value: 52 * 억, ltv_ratio: 67.3, risk_grade: 'B', status: 'ACTIVE', visibility: 'VIP', description: '테헤란로 대형 오피스 12층 전체. 공실률 30%.', deadline: '2026-04-25', delinquency_months: 15, area_sqm: 820, debtor_count: 1, created_at: '2026-01-20' },
  { id: 'lst-o02', seller_id: 'user-s2', institution: '신한은행', title: '여의도 오피스 빌딩 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '서울 영등포구 여의대로 108', principal_amount: 68 * 억, appraised_value: 95 * 억, ltv_ratio: 71.6, risk_grade: 'C', status: 'ACTIVE', visibility: 'VIP', description: '여의도 오피스빌딩 B1~5F. 임차인 다수.', deadline: '2026-05-01', delinquency_months: 20, area_sqm: 2400, debtor_count: 1, created_at: '2026-02-01' },
  { id: 'lst-o03', seller_id: 'user-s3', institution: '하나은행', title: '종로구 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '서울 종로구 종로 150', principal_amount: 15 * 억, appraised_value: 22 * 억, ltv_ratio: 68.2, risk_grade: 'B', status: 'ACTIVE', visibility: 'MEMBERS', description: '종로 오피스 3~5층. 역세권 우수 입지.', deadline: '2026-05-20', delinquency_months: 12, area_sqm: 540, debtor_count: 1, created_at: '2026-02-18' },
  { id: 'lst-o04', seller_id: 'user-s4', institution: '우리은행', title: '구로구 디지털단지 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '서울 구로구 디지털로 300', principal_amount: 8.5 * 억, appraised_value: 13 * 억, ltv_ratio: 65.4, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '구로 디지털단지 오피스 전용 320㎡.', deadline: '2026-06-10', delinquency_months: 16, area_sqm: 320, debtor_count: 1, created_at: '2026-03-02' },
  { id: 'lst-o05', seller_id: 'user-s1', institution: 'KB국민은행', title: '판교 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '경기 성남시 분당구 판교역로 235', principal_amount: 22 * 억, appraised_value: 30 * 억, ltv_ratio: 73.3, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '판교 테크노밸리 오피스 8층. IT기업 밀집지역.', deadline: '2026-05-25', delinquency_months: 22, area_sqm: 660, debtor_count: 1, created_at: '2026-01-30' },
  { id: 'lst-o06', seller_id: 'user-s2', institution: '신한은행', title: '마포구 상암동 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '서울 마포구 성암로 330', principal_amount: 12 * 억, appraised_value: 18 * 억, ltv_ratio: 66.7, risk_grade: 'B', status: 'PENDING', visibility: 'PUBLIC', description: 'DMC 인근 오피스 5층 전체.', deadline: '2026-06-30', delinquency_months: 13, area_sqm: 450, debtor_count: 1, created_at: '2026-03-12' },
  { id: 'lst-o07', seller_id: 'user-s3', institution: '하나은행', title: '서초구 서초동 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '서울 서초구 서초대로 398', principal_amount: 42 * 억, appraised_value: 58 * 억, ltv_ratio: 72.4, risk_grade: 'C', status: 'ACTIVE', visibility: 'VIP', description: '서초동 법조타운 인근 오피스빌딩 지상6층.', deadline: '2026-04-15', delinquency_months: 28, area_sqm: 1100, debtor_count: 2, created_at: '2026-01-10' },
  { id: 'lst-o08', seller_id: 'user-s4', institution: '우리은행', title: '부산 해운대 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '부산 해운대구 센텀중앙로 97', principal_amount: 10 * 억, appraised_value: 16 * 억, ltv_ratio: 62.5, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '센텀시티 오피스 4층. 입지 우수.', deadline: '2026-07-01', delinquency_months: 10, area_sqm: 380, debtor_count: 1, created_at: '2026-03-15' },
  { id: 'lst-o09', seller_id: 'user-s1', institution: 'KB국민은행', title: '대구 수성구 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '대구 수성구 동대구로 350', principal_amount: 6 * 억, appraised_value: 9.2 * 억, ltv_ratio: 65.2, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '수성구 오피스 3층 전체.', deadline: '2026-06-15', delinquency_months: 14, area_sqm: 280, debtor_count: 1, created_at: '2026-02-25' },
  { id: 'lst-o10', seller_id: 'user-s2', institution: '신한은행', title: '광주 서구 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '광주 서구 상무중앙로 110', principal_amount: 4.5 * 억, appraised_value: 7 * 억, ltv_ratio: 64.3, risk_grade: 'B', status: 'CLOSED', visibility: 'PUBLIC', description: '상무지구 오피스 2층.', deadline: '2026-03-15', delinquency_months: 18, area_sqm: 200, debtor_count: 1, created_at: '2026-01-05' },

  // ── 상가/근생 10건 ──────────────────────────────────────
  { id: 'lst-c01', seller_id: 'user-s3', institution: '하나은행', title: '강남역 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '서울 강남구 강남대로 396 B1층', principal_amount: 9 * 억, appraised_value: 15 * 억, ltv_ratio: 60.0, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '강남역 지하상가 A구역 15호. 유동인구 최다.', deadline: '2026-05-30', delinquency_months: 8, area_sqm: 66, debtor_count: 1, created_at: '2026-02-22' },
  { id: 'lst-c02', seller_id: 'user-s4', institution: '우리은행', title: '홍대입구 근린상가 NPL', listing_type: 'NPL', collateral_type: '근린생활', address: '서울 마포구 양화로 160 1층', principal_amount: 7 * 억, appraised_value: 11 * 억, ltv_ratio: 63.6, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '홍대 메인거리 1층 근생. 카페 운영 가능.', deadline: '2026-06-15', delinquency_months: 11, area_sqm: 82, debtor_count: 1, created_at: '2026-03-01' },
  { id: 'lst-c03', seller_id: 'user-s1', institution: 'KB국민은행', title: '이태원 상가건물 NPL', listing_type: 'NPL', collateral_type: '상가', address: '서울 용산구 이태원로 200', principal_amount: 20 * 억, appraised_value: 28 * 억, ltv_ratio: 71.4, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '이태원 상가건물 지상3층. 공실 50%.', deadline: '2026-04-30', delinquency_months: 30, area_sqm: 330, debtor_count: 1, created_at: '2026-01-18' },
  { id: 'lst-c04', seller_id: 'user-s2', institution: '신한은행', title: '부산 서면 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '부산 부산진구 중앙대로 672', principal_amount: 5 * 억, appraised_value: 7.5 * 억, ltv_ratio: 66.7, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '서면 먹자골목 1층 상가.', deadline: '2026-06-30', delinquency_months: 15, area_sqm: 55, debtor_count: 1, created_at: '2026-03-05' },
  { id: 'lst-c05', seller_id: 'user-s3', institution: '하나은행', title: '대전 은행동 근생 NPL', listing_type: 'NPL', collateral_type: '근린생활', address: '대전 중구 중앙로 121', principal_amount: 3.5 * 억, appraised_value: 5.5 * 억, ltv_ratio: 63.6, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '은행동 로데오거리 1~2층 근생.', deadline: '2026-07-15', delinquency_months: 13, area_sqm: 120, debtor_count: 1, created_at: '2026-02-12' },
  { id: 'lst-c06', seller_id: 'user-s4', institution: '우리은행', title: '수원 인계동 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '경기 수원시 팔달구 인계로 155', principal_amount: 4 * 억, appraised_value: 6 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '수원 인계동 먹자거리 상가 1층.', deadline: '2026-06-20', delinquency_months: 20, area_sqm: 48, debtor_count: 2, created_at: '2026-03-08' },
  { id: 'lst-c07', seller_id: 'user-s1', institution: 'KB국민은행', title: '제주 연동 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '제주 제주시 노련로 80', principal_amount: 6 * 억, appraised_value: 10 * 억, ltv_ratio: 60.0, risk_grade: 'B', status: 'PENDING', visibility: 'PUBLIC', description: '제주 연동 관광상권 1층 상가.', deadline: '2026-07-30', delinquency_months: 9, area_sqm: 95, debtor_count: 1, created_at: '2026-03-18' },
  { id: 'lst-c08', seller_id: 'user-s2', institution: '신한은행', title: '강릉 교동 근생 NPL', listing_type: 'NPL', collateral_type: '근린생활', address: '강원 강릉시 경강로 2100', principal_amount: 2 * 억, appraised_value: 3.2 * 억, ltv_ratio: 62.5, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '강릉 도심 근생 1~2층.', deadline: '2026-08-01', delinquency_months: 24, area_sqm: 150, debtor_count: 1, created_at: '2026-02-05' },
  { id: 'lst-c09', seller_id: 'user-s3', institution: '하나은행', title: '청주 상당구 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '충북 청주시 상당구 상당로 100', principal_amount: 1.8 * 억, appraised_value: 2.8 * 억, ltv_ratio: 64.3, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '청주 성안길 상권 상가.', deadline: '2026-07-15', delinquency_months: 22, area_sqm: 42, debtor_count: 1, created_at: '2026-01-28' },
  { id: 'lst-c10', seller_id: 'user-s4', institution: '우리은행', title: '천안 신부동 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '충남 천안시 동남구 만남로 58', principal_amount: 2.5 * 억, appraised_value: 4 * 억, ltv_ratio: 62.5, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '천안역 인근 1층 상가.', deadline: '2026-06-25', delinquency_months: 16, area_sqm: 60, debtor_count: 1, created_at: '2026-03-11' },

  // ── 토지/임야 10건 ──────────────────────────────────────
  { id: 'lst-l01', seller_id: 'user-s1', institution: 'KB국민은행', title: '화성시 동탄 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '경기 화성시 동탄면 석우리 산 12', principal_amount: 30 * 억, appraised_value: 42 * 억, ltv_ratio: 71.4, risk_grade: 'C', status: 'ACTIVE', visibility: 'VIP', description: '동탄2 인근 개발예정지 토지 3,300㎡.', deadline: '2026-05-15', delinquency_months: 26, area_sqm: 3300, debtor_count: 1, created_at: '2026-01-12' },
  { id: 'lst-l02', seller_id: 'user-s2', institution: '신한은행', title: '파주시 문산읍 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '경기 파주시 문산읍 선유리 280', principal_amount: 8 * 억, appraised_value: 11 * 억, ltv_ratio: 72.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '파주 문산 준농림지 토지 5,000㎡. 창고부지 적합.', deadline: '2026-06-30', delinquency_months: 36, area_sqm: 5000, debtor_count: 1, created_at: '2026-02-08' },
  { id: 'lst-l03', seller_id: 'user-s3', institution: '하나은행', title: '양평군 임야 NPL', listing_type: 'NPL', collateral_type: '임야', address: '경기 양평군 양서면 복포리 산 88', principal_amount: 3 * 억, appraised_value: 5 * 억, ltv_ratio: 60.0, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '양평 남한강변 임야 10,000㎡. 전원주택 가능.', deadline: '2026-08-15', delinquency_months: 48, area_sqm: 10000, debtor_count: 2, created_at: '2026-01-05' },
  { id: 'lst-l04', seller_id: 'user-s4', institution: '우리은행', title: '세종시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '세종 조치원읍 신안리 155', principal_amount: 15 * 억, appraised_value: 20 * 억, ltv_ratio: 75.0, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '세종시 행정중심복합도시 인근 토지.', deadline: '2026-05-20', delinquency_months: 30, area_sqm: 2200, debtor_count: 1, created_at: '2026-02-15' },
  { id: 'lst-l05', seller_id: 'user-s1', institution: 'KB국민은행', title: '제주 서귀포 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '제주 서귀포시 안덕면 화순리 320', principal_amount: 10 * 억, appraised_value: 16 * 억, ltv_ratio: 62.5, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '서귀포 해안 인접 토지. 관광개발 가능.', deadline: '2026-07-01', delinquency_months: 20, area_sqm: 6600, debtor_count: 1, created_at: '2026-03-01' },
  { id: 'lst-l06', seller_id: 'user-s2', institution: '신한은행', title: '춘천시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '강원 춘천시 동면 감정리 77', principal_amount: 2 * 억, appraised_value: 3.5 * 억, ltv_ratio: 57.1, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '춘천 의암호 인근 토지 2,000㎡.', deadline: '2026-09-01', delinquency_months: 40, area_sqm: 2000, debtor_count: 1, created_at: '2026-01-22' },
  { id: 'lst-l07', seller_id: 'user-s3', institution: '하나은행', title: '포천시 임야 NPL', listing_type: 'NPL', collateral_type: '임야', address: '경기 포천시 소흘읍 이동교리 산 55', principal_amount: 1.5 * 억, appraised_value: 2.5 * 억, ltv_ratio: 60.0, risk_grade: 'D', status: 'EXPIRED', visibility: 'PUBLIC', description: '포천 임야 8,000㎡. 접근성 제한.', deadline: '2026-02-28', delinquency_months: 50, area_sqm: 8000, debtor_count: 3, created_at: '2025-12-15' },
  { id: 'lst-l08', seller_id: 'user-s4', institution: '우리은행', title: '김포시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '경기 김포시 양촌읍 학운리 200', principal_amount: 12 * 억, appraised_value: 18 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '김포 물류단지 인근 토지 4,000㎡.', deadline: '2026-06-15', delinquency_months: 18, area_sqm: 4000, debtor_count: 1, created_at: '2026-02-28' },
  { id: 'lst-l09', seller_id: 'user-s1', institution: 'KB국민은행', title: '평택시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '경기 평택시 팽성읍 안정리 150', principal_amount: 18 * 억, appraised_value: 25 * 억, ltv_ratio: 72.0, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '평택 삼성반도체 인근 산업용지.', deadline: '2026-05-30', delinquency_months: 24, area_sqm: 5500, debtor_count: 1, created_at: '2026-01-08' },
  { id: 'lst-l10', seller_id: 'user-s2', institution: '신한은행', title: '여주시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '경기 여주시 대신면 천서리 95', principal_amount: 1.2 * 억, appraised_value: 2 * 억, ltv_ratio: 60.0, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '여주 전원지역 토지 1,500㎡.', deadline: '2026-08-30', delinquency_months: 42, area_sqm: 1500, debtor_count: 1, created_at: '2026-02-18' },

  // ── 다세대/공장/기타 10건 ───────────────────────────────
  { id: 'lst-m01', seller_id: 'user-s3', institution: '하나은행', title: '관악구 신림동 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '서울 관악구 신림로 340', principal_amount: 3 * 억, appraised_value: 4.5 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '신림동 다세대 4층 건물 전체. 임차인 8세대.', deadline: '2026-06-30', delinquency_months: 22, area_sqm: 240, debtor_count: 1, created_at: '2026-02-14' },
  { id: 'lst-m02', seller_id: 'user-s4', institution: '우리은행', title: '안산시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '경기 안산시 단원구 원시동 780', principal_amount: 25 * 억, appraised_value: 35 * 억, ltv_ratio: 71.4, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '반월공단 공장 부지 및 건물. 가동 중단.', deadline: '2026-05-15', delinquency_months: 32, area_sqm: 3000, debtor_count: 1, created_at: '2026-01-25' },
  { id: 'lst-m03', seller_id: 'user-s1', institution: 'KB국민은행', title: '시흥시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '경기 시흥시 정왕동 시화공단 3로 22', principal_amount: 18 * 억, appraised_value: 26 * 억, ltv_ratio: 69.2, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '시화공단 공장 1,800㎡. 기계설비 포함.', deadline: '2026-06-20', delinquency_months: 28, area_sqm: 1800, debtor_count: 2, created_at: '2026-02-05' },
  { id: 'lst-m04', seller_id: 'user-s2', institution: '신한은행', title: '은평구 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '서울 은평구 불광로 88', principal_amount: 4.5 * 억, appraised_value: 7 * 억, ltv_ratio: 64.3, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '불광동 다세대 5층. 임차인 6세대. 역세권.', deadline: '2026-07-01', delinquency_months: 14, area_sqm: 300, debtor_count: 1, created_at: '2026-03-02' },
  { id: 'lst-m05', seller_id: 'user-s3', institution: '하나은행', title: '인천 남동구 물류창고 NPL', listing_type: 'NPL', collateral_type: '창고', address: '인천 남동구 남동대로 150', principal_amount: 15 * 억, appraised_value: 22 * 억, ltv_ratio: 68.2, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '남동공단 물류창고 2,500㎡. 냉동시설 포함.', deadline: '2026-06-10', delinquency_months: 19, area_sqm: 2500, debtor_count: 1, created_at: '2026-02-20' },
  { id: 'lst-m06', seller_id: 'user-s4', institution: '우리은행', title: '김해시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '경남 김해시 진영읍 진영로 580', principal_amount: 8 * 억, appraised_value: 12 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '진영 산업단지 공장. 자동차부품 제조시설.', deadline: '2026-07-15', delinquency_months: 25, area_sqm: 2200, debtor_count: 1, created_at: '2026-01-30' },
  { id: 'lst-m07', seller_id: 'user-s1', institution: 'KB국민은행', title: '동작구 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '서울 동작구 사당로 180', principal_amount: 5 * 억, appraised_value: 8 * 억, ltv_ratio: 62.5, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '사당동 다세대 3층 건물. 임차인 4세대.', deadline: '2026-06-25', delinquency_months: 11, area_sqm: 180, debtor_count: 1, created_at: '2026-03-10' },
  { id: 'lst-m08', seller_id: 'user-s2', institution: '신한은행', title: '수원 권선구 다가구 NPL', listing_type: 'NPL', collateral_type: '다가구', address: '경기 수원시 권선구 권선로 250', principal_amount: 3.8 * 억, appraised_value: 6 * 억, ltv_ratio: 63.3, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '수원 다가구주택 4층. 원룸 12실.', deadline: '2026-07-30', delinquency_months: 16, area_sqm: 260, debtor_count: 1, created_at: '2026-02-28' },
  { id: 'lst-m09', seller_id: 'user-s3', institution: '하나은행', title: '광주 북구 모텔 NPL', listing_type: 'NPL', collateral_type: '숙박시설', address: '광주 북구 용봉동 하서로 220', principal_amount: 7 * 억, appraised_value: 10 * 억, ltv_ratio: 70.0, risk_grade: 'D', status: 'ACTIVE', visibility: 'MEMBERS', description: '광주 용봉동 모텔 건물. 객실 30실.', deadline: '2026-08-15', delinquency_months: 35, area_sqm: 500, debtor_count: 1, created_at: '2026-01-15' },
  { id: 'lst-m10', seller_id: 'user-s4', institution: '우리은행', title: '원주시 주유소 NPL', listing_type: 'NPL', collateral_type: '주유소', address: '강원 원주시 북원로 350', principal_amount: 5 * 억, appraised_value: 8.5 * 억, ltv_ratio: 58.8, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '원주 주유소 부지 및 시설. 환경조사 필요.', deadline: '2026-09-01', delinquency_months: 40, area_sqm: 800, debtor_count: 1, created_at: '2026-02-10' },

  // ── 추가 50건 (아파트/빌라/오피스/상가/토지/공장/다세대/모텔/주유소/창고) ──

  // 아파트 추가 5건
  { id: 'lst-a11', seller_id: 'user-s1', institution: 'NH농협은행', title: '울산 남구 삼산동 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '울산 남구 삼산로 85', principal_amount: 4.8 * 억, appraised_value: 7.2 * 억, ltv_ratio: 66.7, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '삼산동 현대아파트 전용 84㎡. 역세권.', deadline: '2026-05-31', delinquency_months: 12, area_sqm: 84, debtor_count: 1, created_at: '2026-03-01' },
  { id: 'lst-a12', seller_id: 'user-s2', institution: 'IBK기업은행', title: '세종시 나성동 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '세종 나성동 보듬로 120', principal_amount: 5.2 * 억, appraised_value: 8 * 억, ltv_ratio: 65.0, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '세종시 나성동 전용 74㎡. 행복도시 중심.', deadline: '2026-06-30', delinquency_months: 9, area_sqm: 74, debtor_count: 1, created_at: '2026-02-28' },
  { id: 'lst-a13', seller_id: 'user-s3', institution: '한국자산관리공사', title: '광주 서구 치평동 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '광주 서구 시청로 55', principal_amount: 3.5 * 억, appraised_value: 5.5 * 억, ltv_ratio: 63.6, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '치평동 아파트 전용 59㎡. 시청 인근.', deadline: '2026-07-15', delinquency_months: 15, area_sqm: 59, debtor_count: 1, created_at: '2026-03-05' },
  { id: 'lst-a14', seller_id: 'user-s4', institution: '유암코', title: '대구 달서구 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '대구 달서구 달구벌대로 1200', principal_amount: 6.8 * 억, appraised_value: 10.5 * 억, ltv_ratio: 64.8, risk_grade: 'B', status: 'PENDING', visibility: 'PUBLIC', description: '달서구 월성동 아파트 전용 101㎡.', deadline: '2026-08-01', delinquency_months: 10, area_sqm: 101, debtor_count: 1, created_at: '2026-03-12' },
  { id: 'lst-a15', seller_id: 'user-s1', institution: '대신F&I', title: '경남 창원시 아파트 NPL', listing_type: 'NPL', collateral_type: '아파트', address: '경남 창원시 성산구 상남로 60', principal_amount: 3.9 * 억, appraised_value: 6 * 억, ltv_ratio: 65.0, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '창원 상남동 전용 84㎡. 상남상업지구.', deadline: '2026-06-20', delinquency_months: 18, area_sqm: 84, debtor_count: 1, created_at: '2026-02-15' },

  // 빌라 5건
  { id: 'lst-v01', seller_id: 'user-s2', institution: 'SBI저축은행', title: '서울 강서구 빌라 NPL', listing_type: 'NPL', collateral_type: '빌라', address: '서울 강서구 화곡로 220', principal_amount: 2.8 * 억, appraised_value: 4.3 * 억, ltv_ratio: 65.1, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '화곡동 빌라 3층. 전용 56㎡.', deadline: '2026-07-01', delinquency_months: 20, area_sqm: 56, debtor_count: 1, created_at: '2026-02-20' },
  { id: 'lst-v02', seller_id: 'user-s3', institution: 'NH농협은행', title: '부산 사상구 빌라 NPL', listing_type: 'NPL', collateral_type: '빌라', address: '부산 사상구 사상로 320', principal_amount: 1.8 * 억, appraised_value: 2.8 * 억, ltv_ratio: 64.3, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '사상구 빌라 2층. 전용 49㎡.', deadline: '2026-08-15', delinquency_months: 24, area_sqm: 49, debtor_count: 1, created_at: '2026-01-25' },
  { id: 'lst-v03', seller_id: 'user-s4', institution: 'IBK기업은행', title: '인천 부평구 빌라 NPL', listing_type: 'NPL', collateral_type: '빌라', address: '인천 부평구 부평대로 150', principal_amount: 2.2 * 억, appraised_value: 3.5 * 억, ltv_ratio: 62.9, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '부평역 인근 빌라 4층. 전용 52㎡.', deadline: '2026-07-30', delinquency_months: 22, area_sqm: 52, debtor_count: 1, created_at: '2026-03-08' },
  { id: 'lst-v04', seller_id: 'user-s1', institution: '대신F&I', title: '경기 의정부시 빌라 NPL', listing_type: 'NPL', collateral_type: '빌라', address: '경기 의정부시 평화로 200', principal_amount: 1.5 * 억, appraised_value: 2.4 * 억, ltv_ratio: 62.5, risk_grade: 'D', status: 'CLOSED', visibility: 'PUBLIC', description: '의정부역 인근 빌라. 전용 43㎡.', deadline: '2026-03-31', delinquency_months: 30, area_sqm: 43, debtor_count: 1, created_at: '2026-01-10' },
  { id: 'lst-v05', seller_id: 'user-s2', institution: '유암코', title: '대전 서구 빌라 NPL', listing_type: 'NPL', collateral_type: '빌라', address: '대전 서구 둔산로 88', principal_amount: 2.5 * 억, appraised_value: 3.8 * 억, ltv_ratio: 65.8, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '둔산동 빌라 3층. 전용 59㎡.', deadline: '2026-06-15', delinquency_months: 16, area_sqm: 59, debtor_count: 1, created_at: '2026-02-18' },

  // 오피스 추가 5건
  { id: 'lst-o11', seller_id: 'user-s3', institution: '한국자산관리공사', title: '울산 남구 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '울산 남구 삼산중로 100', principal_amount: 15 * 억, appraised_value: 22 * 억, ltv_ratio: 68.2, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '삼산동 오피스 빌딩 3~5층.', deadline: '2026-06-30', delinquency_months: 18, area_sqm: 480, debtor_count: 1, created_at: '2026-02-10' },
  { id: 'lst-o12', seller_id: 'user-s4', institution: 'NH농협은행', title: '전북 전주시 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '전북 전주시 완산구 현무1길 20', principal_amount: 8 * 억, appraised_value: 12.5 * 억, ltv_ratio: 64.0, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '전주 객사 인근 오피스 2~4층.', deadline: '2026-07-15', delinquency_months: 14, area_sqm: 360, debtor_count: 1, created_at: '2026-03-02' },
  { id: 'lst-o13', seller_id: 'user-s1', institution: 'SBI저축은행', title: '충남 아산시 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '충남 아산시 배방읍 장재로 15', principal_amount: 10 * 억, appraised_value: 15 * 억, ltv_ratio: 66.7, risk_grade: 'B', status: 'PENDING', visibility: 'PUBLIC', description: '아산 배방 신도시 오피스 5층 전체.', deadline: '2026-08-01', delinquency_months: 12, area_sqm: 520, debtor_count: 1, created_at: '2026-03-15' },
  { id: 'lst-o14', seller_id: 'user-s2', institution: 'IBK기업은행', title: '경북 포항시 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '경북 포항시 북구 중앙로 250', principal_amount: 5.5 * 억, appraised_value: 8.5 * 억, ltv_ratio: 64.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '포항 시내 오피스 3층 전체.', deadline: '2026-07-20', delinquency_months: 20, area_sqm: 290, debtor_count: 1, created_at: '2026-02-05' },
  { id: 'lst-o15', seller_id: 'user-s3', institution: '대신F&I', title: '경기 안양시 오피스 NPL', listing_type: 'NPL', collateral_type: '오피스', address: '경기 안양시 만안구 안양로 200', principal_amount: 12 * 억, appraised_value: 18 * 억, ltv_ratio: 66.7, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '안양역 인근 오피스 빌딩 4~6층.', deadline: '2026-06-25', delinquency_months: 15, area_sqm: 600, debtor_count: 1, created_at: '2026-01-28' },

  // 상가 추가 5건
  { id: 'lst-c11', seller_id: 'user-s4', institution: '유암코', title: '전남 순천시 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '전남 순천시 장천동 중앙로 50', principal_amount: 3 * 억, appraised_value: 4.8 * 억, ltv_ratio: 62.5, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '순천 장천동 1층 상가. 상권 양호.', deadline: '2026-07-01', delinquency_months: 18, area_sqm: 55, debtor_count: 1, created_at: '2026-02-12' },
  { id: 'lst-c12', seller_id: 'user-s1', institution: 'NH농협은행', title: '경남 김해시 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '경남 김해시 내외동 가야로 300', principal_amount: 4.5 * 억, appraised_value: 7 * 억, ltv_ratio: 64.3, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '내외동 상업지구 1층 상가.', deadline: '2026-08-15', delinquency_months: 13, area_sqm: 72, debtor_count: 1, created_at: '2026-03-10' },
  { id: 'lst-c13', seller_id: 'user-s2', institution: 'SBI저축은행', title: '충북 청주시 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '충북 청주시 흥덕구 복대로 80', principal_amount: 2.8 * 억, appraised_value: 4.2 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'CLOSED', visibility: 'PUBLIC', description: '복대동 상가 1층. 복대사거리 인근.', deadline: '2026-03-20', delinquency_months: 25, area_sqm: 45, debtor_count: 1, created_at: '2025-12-20' },
  { id: 'lst-c14', seller_id: 'user-s3', institution: '한국자산관리공사', title: '제주 서귀포 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '제주 서귀포시 중앙로 100', principal_amount: 5.5 * 억, appraised_value: 8.5 * 억, ltv_ratio: 64.7, risk_grade: 'B', status: 'ACTIVE', visibility: 'MEMBERS', description: '서귀포 중심 상권 1~2층 상가.', deadline: '2026-07-30', delinquency_months: 11, area_sqm: 110, debtor_count: 1, created_at: '2026-03-01' },
  { id: 'lst-c15', seller_id: 'user-s4', institution: 'IBK기업은행', title: '강원 원주시 상가 NPL', listing_type: 'NPL', collateral_type: '상가', address: '강원 원주시 원일로 190', principal_amount: 1.8 * 억, appraised_value: 3 * 억, ltv_ratio: 60.0, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '원주 혁신도시 인근 상가.', deadline: '2026-09-01', delinquency_months: 22, area_sqm: 38, debtor_count: 1, created_at: '2026-02-25' },

  // 토지 추가 5건
  { id: 'lst-l11', seller_id: 'user-s1', institution: '유암코', title: '충남 논산시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '충남 논산시 연무읍 연무로 500', principal_amount: 6 * 억, appraised_value: 9 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '연무읍 산업용 토지 3,500㎡.', deadline: '2026-07-15', delinquency_months: 28, area_sqm: 3500, debtor_count: 1, created_at: '2026-01-20' },
  { id: 'lst-l12', seller_id: 'user-s2', institution: 'NH농협은행', title: '전북 익산시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '전북 익산시 금마면 금마로 200', principal_amount: 3.5 * 억, appraised_value: 5.5 * 억, ltv_ratio: 63.6, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '익산 금마면 농지 4,200㎡.', deadline: '2026-09-15', delinquency_months: 36, area_sqm: 4200, debtor_count: 2, created_at: '2026-02-08' },
  { id: 'lst-l13', seller_id: 'user-s3', institution: '대신F&I', title: '경북 경주시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '경북 경주시 외동읍 입실리 350', principal_amount: 8 * 억, appraised_value: 12 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'PENDING', visibility: 'PUBLIC', description: '경주 외동읍 관광개발 가능 토지.', deadline: '2026-08-01', delinquency_months: 20, area_sqm: 5500, debtor_count: 1, created_at: '2026-03-18' },
  { id: 'lst-l14', seller_id: 'user-s4', institution: 'SBI저축은행', title: '강원 속초시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '강원 속초시 대포동 해안로 80', principal_amount: 12 * 억, appraised_value: 18 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'VIP', description: '속초 해안가 토지 2,800㎡. 숙박시설 가능.', deadline: '2026-07-01', delinquency_months: 16, area_sqm: 2800, debtor_count: 1, created_at: '2026-02-15' },
  { id: 'lst-l15', seller_id: 'user-s1', institution: '한국자산관리공사', title: '전남 목포시 토지 NPL', listing_type: 'NPL', collateral_type: '토지', address: '전남 목포시 하당동 영산로 450', principal_amount: 4 * 억, appraised_value: 6.5 * 억, ltv_ratio: 61.5, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '목포 하당 신도시 상업용 토지.', deadline: '2026-08-30', delinquency_months: 24, area_sqm: 1800, debtor_count: 1, created_at: '2026-01-30' },

  // 공장 추가 5건
  { id: 'lst-f01', seller_id: 'user-s2', institution: 'IBK기업은행', title: '경기 화성시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '경기 화성시 팔탄면 시청로 600', principal_amount: 35 * 억, appraised_value: 50 * 억, ltv_ratio: 70.0, risk_grade: 'C', status: 'ACTIVE', visibility: 'VIP', description: '팔탄 산업단지 제조공장 4,500㎡. 설비 포함.', deadline: '2026-06-30', delinquency_months: 22, area_sqm: 4500, debtor_count: 1, created_at: '2026-02-01' },
  { id: 'lst-f02', seller_id: 'user-s3', institution: '유암코', title: '충남 천안시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '충남 천안시 서북구 직산읍 부성로 90', principal_amount: 20 * 억, appraised_value: 30 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '직산 산업단지 공장. 반도체 부품 제조.', deadline: '2026-07-15', delinquency_months: 26, area_sqm: 3200, debtor_count: 1, created_at: '2026-01-15' },
  { id: 'lst-f03', seller_id: 'user-s4', institution: '대신F&I', title: '경남 양산시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '경남 양산시 물금읍 범어로 200', principal_amount: 45 * 억, appraised_value: 65 * 억, ltv_ratio: 69.2, risk_grade: 'C', status: 'ACTIVE', visibility: 'VIP', description: '양산 물금 물류센터 겸 공장 6,000㎡.', deadline: '2026-05-30', delinquency_months: 30, area_sqm: 6000, debtor_count: 2, created_at: '2026-01-08' },
  { id: 'lst-f04', seller_id: 'user-s1', institution: 'NH농협은행', title: '전남 광양시 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '전남 광양시 광양읍 제철로 180', principal_amount: 28 * 억, appraised_value: 40 * 억, ltv_ratio: 70.0, risk_grade: 'D', status: 'ACTIVE', visibility: 'MEMBERS', description: '광양 산업단지 철강 관련 공장.', deadline: '2026-08-15', delinquency_months: 35, area_sqm: 5200, debtor_count: 1, created_at: '2026-02-20' },
  { id: 'lst-f05', seller_id: 'user-s2', institution: 'SBI저축은행', title: '충북 음성군 공장 NPL', listing_type: 'NPL', collateral_type: '공장', address: '충북 음성군 맹동면 산업로 55', principal_amount: 15 * 억, appraised_value: 22 * 억, ltv_ratio: 68.2, risk_grade: 'C', status: 'CLOSED', visibility: 'PUBLIC', description: '음성 식품공장 2,800㎡. 가동 중단.', deadline: '2026-04-01', delinquency_months: 28, area_sqm: 2800, debtor_count: 1, created_at: '2025-12-10' },

  // 다세대 추가 5건
  { id: 'lst-d01', seller_id: 'user-s3', institution: '한국자산관리공사', title: '서울 성북구 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '서울 성북구 정릉로 280', principal_amount: 5.5 * 억, appraised_value: 8.5 * 억, ltv_ratio: 64.7, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '정릉동 다세대 5층. 임차인 10세대.', deadline: '2026-06-15', delinquency_months: 14, area_sqm: 320, debtor_count: 1, created_at: '2026-03-05' },
  { id: 'lst-d02', seller_id: 'user-s4', institution: 'NH농협은행', title: '부산 북구 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '부산 북구 화명동 금곡대로 180', principal_amount: 3.2 * 억, appraised_value: 5 * 억, ltv_ratio: 64.0, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '화명동 다세대 4층. 임차인 6세대.', deadline: '2026-07-30', delinquency_months: 20, area_sqm: 240, debtor_count: 1, created_at: '2026-02-22' },
  { id: 'lst-d03', seller_id: 'user-s1', institution: 'IBK기업은행', title: '인천 서구 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '인천 서구 검단로 150', principal_amount: 4 * 억, appraised_value: 6.2 * 억, ltv_ratio: 64.5, risk_grade: 'B', status: 'PENDING', visibility: 'PUBLIC', description: '검단신도시 인근 다세대 3층.', deadline: '2026-08-01', delinquency_months: 11, area_sqm: 200, debtor_count: 1, created_at: '2026-03-15' },
  { id: 'lst-d04', seller_id: 'user-s2', institution: '대신F&I', title: '대구 동구 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '대구 동구 동촌로 90', principal_amount: 2.8 * 억, appraised_value: 4.3 * 억, ltv_ratio: 65.1, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '동촌동 다세대 4층. 임차인 5세대.', deadline: '2026-07-15', delinquency_months: 22, area_sqm: 180, debtor_count: 1, created_at: '2026-01-18' },
  { id: 'lst-d05', seller_id: 'user-s3', institution: '유암코', title: '경기 고양시 다세대 NPL', listing_type: 'NPL', collateral_type: '다세대', address: '경기 고양시 덕양구 행신로 250', principal_amount: 6 * 억, appraised_value: 9 * 억, ltv_ratio: 66.7, risk_grade: 'B', status: 'ACTIVE', visibility: 'PUBLIC', description: '행신동 역세권 다세대 5층 전체.', deadline: '2026-06-30', delinquency_months: 13, area_sqm: 350, debtor_count: 1, created_at: '2026-03-08' },

  // 모텔/숙박 5건
  { id: 'lst-h01', seller_id: 'user-s4', institution: 'SBI저축은행', title: '부산 중구 모텔 NPL', listing_type: 'NPL', collateral_type: '숙박시설', address: '부산 중구 중앙대로 50', principal_amount: 12 * 억, appraised_value: 18 * 억, ltv_ratio: 66.7, risk_grade: 'D', status: 'ACTIVE', visibility: 'MEMBERS', description: '부산 중앙동 모텔. 객실 45실. 남포동 인근.', deadline: '2026-07-15', delinquency_months: 32, area_sqm: 680, debtor_count: 1, created_at: '2026-02-01' },
  { id: 'lst-h02', seller_id: 'user-s1', institution: '한국자산관리공사', title: '강원 강릉시 모텔 NPL', listing_type: 'NPL', collateral_type: '숙박시설', address: '강원 강릉시 경포로 450', principal_amount: 8 * 억, appraised_value: 13 * 억, ltv_ratio: 61.5, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '경포해수욕장 인근 모텔 35실.', deadline: '2026-08-01', delinquency_months: 20, area_sqm: 520, debtor_count: 1, created_at: '2026-03-01' },
  { id: 'lst-h03', seller_id: 'user-s2', institution: '유암코', title: '경기 가평군 펜션단지 NPL', listing_type: 'NPL', collateral_type: '숙박시설', address: '경기 가평군 청평면 호반로 180', principal_amount: 15 * 억, appraised_value: 23 * 억, ltv_ratio: 65.2, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '청평호 인근 펜션단지 10동. 부지 3,000㎡.', deadline: '2026-06-30', delinquency_months: 18, area_sqm: 3000, debtor_count: 1, created_at: '2026-02-15' },
  { id: 'lst-h04', seller_id: 'user-s3', institution: 'NH농협은행', title: '제주 제주시 게스트하우스 NPL', listing_type: 'NPL', collateral_type: '숙박시설', address: '제주 제주시 탑동로 90', principal_amount: 6 * 억, appraised_value: 9.5 * 억, ltv_ratio: 63.2, risk_grade: 'C', status: 'EXPIRED', visibility: 'PUBLIC', description: '제주 탑동 게스트하우스 20실.', deadline: '2026-03-15', delinquency_months: 26, area_sqm: 380, debtor_count: 1, created_at: '2025-12-01' },
  { id: 'lst-h05', seller_id: 'user-s4', institution: '대신F&I', title: '충남 보령시 모텔 NPL', listing_type: 'NPL', collateral_type: '숙박시설', address: '충남 보령시 대천해수욕장로 200', principal_amount: 5 * 억, appraised_value: 8 * 억, ltv_ratio: 62.5, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '대천해수욕장 인근 모텔 25실.', deadline: '2026-09-01', delinquency_months: 35, area_sqm: 420, debtor_count: 1, created_at: '2026-01-10' },

  // 주유소 5건
  { id: 'lst-g01', seller_id: 'user-s1', institution: 'IBK기업은행', title: '경기 이천시 주유소 NPL', listing_type: 'NPL', collateral_type: '주유소', address: '경기 이천시 부발읍 경충대로 800', principal_amount: 8 * 억, appraised_value: 12 * 억, ltv_ratio: 66.7, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '이천 경충대로변 주유소. 토양오염검사 완료.', deadline: '2026-07-30', delinquency_months: 30, area_sqm: 950, debtor_count: 1, created_at: '2026-02-08' },
  { id: 'lst-g02', seller_id: 'user-s2', institution: 'SBI저축은행', title: '충남 서산시 주유소 NPL', listing_type: 'NPL', collateral_type: '주유소', address: '충남 서산시 읍내동 서산로 120', principal_amount: 6 * 억, appraised_value: 9.5 * 억, ltv_ratio: 63.2, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '서산시내 주유소. 세차장 병행 운영.', deadline: '2026-08-15', delinquency_months: 38, area_sqm: 1100, debtor_count: 1, created_at: '2026-01-22' },
  { id: 'lst-g03', seller_id: 'user-s3', institution: '한국자산관리공사', title: '경남 거제시 주유소 NPL', listing_type: 'NPL', collateral_type: '주유소', address: '경남 거제시 고현동 거제대로 500', principal_amount: 7.5 * 억, appraised_value: 11 * 억, ltv_ratio: 68.2, risk_grade: 'D', status: 'CLOSED', visibility: 'PUBLIC', description: '거제 고현동 주유소. 환경정화 필요.', deadline: '2026-04-15', delinquency_months: 42, area_sqm: 880, debtor_count: 1, created_at: '2025-12-15' },
  { id: 'lst-g04', seller_id: 'user-s4', institution: '유암코', title: '전북 군산시 주유소 NPL', listing_type: 'NPL', collateral_type: '주유소', address: '전북 군산시 조촌동 번영로 300', principal_amount: 5.5 * 억, appraised_value: 8.5 * 억, ltv_ratio: 64.7, risk_grade: 'D', status: 'ACTIVE', visibility: 'PUBLIC', description: '군산 시내 주유소. LPG 충전소 병행.', deadline: '2026-09-01', delinquency_months: 34, area_sqm: 1200, debtor_count: 1, created_at: '2026-02-18' },
  { id: 'lst-g05', seller_id: 'user-s1', institution: 'NH농협은행', title: '경북 구미시 주유소 NPL', listing_type: 'NPL', collateral_type: '주유소', address: '경북 구미시 산동면 인동로 400', principal_amount: 9 * 억, appraised_value: 14 * 억, ltv_ratio: 64.3, risk_grade: 'C', status: 'PENDING', visibility: 'PUBLIC', description: '구미 국가산업단지 인근 주유소.', deadline: '2026-08-01', delinquency_months: 22, area_sqm: 1050, debtor_count: 1, created_at: '2026-03-12' },

  // 창고 5건
  { id: 'lst-w01', seller_id: 'user-s2', institution: '대신F&I', title: '경기 용인시 창고 NPL', listing_type: 'NPL', collateral_type: '창고', address: '경기 용인시 처인구 백암면 용천로 200', principal_amount: 18 * 억, appraised_value: 26 * 억, ltv_ratio: 69.2, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '백암 물류단지 냉장창고 3,800㎡.', deadline: '2026-07-01', delinquency_months: 20, area_sqm: 3800, debtor_count: 1, created_at: '2026-02-10' },
  { id: 'lst-w02', seller_id: 'user-s3', institution: 'IBK기업은행', title: '인천 서구 물류창고 NPL', listing_type: 'NPL', collateral_type: '창고', address: '인천 서구 가좌동 가좌로 350', principal_amount: 25 * 억, appraised_value: 38 * 억, ltv_ratio: 65.8, risk_grade: 'B', status: 'ACTIVE', visibility: 'VIP', description: '인천 서부산업단지 대형 물류창고.', deadline: '2026-06-15', delinquency_months: 16, area_sqm: 5500, debtor_count: 1, created_at: '2026-01-28' },
  { id: 'lst-w03', seller_id: 'user-s4', institution: 'SBI저축은행', title: '경기 광주시 창고 NPL', listing_type: 'NPL', collateral_type: '창고', address: '경기 광주시 오포읍 능평로 120', principal_amount: 10 * 억, appraised_value: 15 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'PUBLIC', description: '오포읍 물류창고 2,200㎡. 주거지역 인접.', deadline: '2026-08-01', delinquency_months: 24, area_sqm: 2200, debtor_count: 1, created_at: '2026-03-05' },
  { id: 'lst-w04', seller_id: 'user-s1', institution: '한국자산관리공사', title: '충남 당진시 창고 NPL', listing_type: 'NPL', collateral_type: '창고', address: '충남 당진시 송악읍 산업로 80', principal_amount: 30 * 억, appraised_value: 45 * 억, ltv_ratio: 66.7, risk_grade: 'C', status: 'ACTIVE', visibility: 'MEMBERS', description: '당진 산업단지 대형 물류창고 7,000㎡.', deadline: '2026-06-30', delinquency_months: 18, area_sqm: 7000, debtor_count: 1, created_at: '2026-01-15' },
  { id: 'lst-w05', seller_id: 'user-s2', institution: '유암코', title: '경기 파주시 창고 NPL', listing_type: 'NPL', collateral_type: '창고', address: '경기 파주시 월롱면 엘지로 55', principal_amount: 22 * 억, appraised_value: 32 * 억, ltv_ratio: 68.8, risk_grade: 'C', status: 'EXPIRED', visibility: 'PUBLIC', description: '파주 물류센터 4,800㎡. 계약 만료.', deadline: '2026-03-01', delinquency_months: 26, area_sqm: 4800, debtor_count: 1, created_at: '2025-11-20' },
]
