import type { Metadata, Viewport } from 'next'
import { headers } from 'next/headers'
import localFont from 'next/font/local'
import './globals.css'

// Pretendard — 한국어 최적화 폰트 (가변 서브셋, woff2)
const pretendard = localFont({
  src: [
    {
      path: '../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2',
      weight: '100 900',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
  display: 'swap',
  preload: true,
  fallback: [
    'Pretendard',
    '-apple-system',
    'BlinkMacSystemFont',
    'system-ui',
    'Helvetica Neue',
    'Apple SD Gothic Neo',
    'Noto Sans KR',
    'sans-serif',
  ],
})
import { AuthProvider } from '@/components/auth/auth-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import { Toaster } from 'sonner'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { AutoTranslateProvider } from '@/components/translate/auto-translate-provider'
import { Analytics } from '@vercel/analytics/next'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://nplatform.co.kr'

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#1B3A5C',
}

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'NPLatform - 국내 최초 AI 기반 NPL 투자 분석 플랫폼',
    template: '%s | NPLatform',
  },
  description:
    'NPLatform은 AI가 분석하는 NPL(부실채권) 투자 분석 및 거래 플랫폼입니다. 전국 NPL 매물 검색, AI 등급 평가, 낙찰가율 예측, 수익률 시뮬레이션까지 한 곳에서.',
  keywords: [
    'NPL', '부실채권', '경매', 'NPL 투자', '부동산 경매', 'AI 분석',
    '낙찰가율', '채권 투자', '법원경매', '투자 분석 플랫폼',
  ],
  authors: [{ name: 'NPLatform', url: SITE_URL }],
  creator: 'NPLatform',
  publisher: 'NPLatform',
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  openGraph: {
    title: 'NPLatform - 국내 최초 AI 기반 NPL 투자 분석 플랫폼',
    description:
      'AI가 분석하는 NPL 투자. 전국 NPL 매물 검색, AI 등급 평가, 수익률 시뮬레이션까지 한 곳에서.',
    url: SITE_URL,
    siteName: 'NPLatform',
    locale: 'ko_KR',
    type: 'website',
    images: [
      {
        url: `${SITE_URL}/og-image.png`,
        width: 1200,
        height: 630,
        alt: 'NPLatform - AI 기반 NPL 투자 분석 플랫폼',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'NPLatform - AI 기반 NPL 투자 분석 플랫폼',
    description: 'AI가 분석하는 NPL 투자. 전국 NPL 매물 검색, AI 등급 평가, 수익률 시뮬레이션.',
    images: [`${SITE_URL}/og-image.png`],
  },
  alternates: {
    canonical: SITE_URL,
    languages: {
      'ko': SITE_URL,
      'en': `${SITE_URL}/en`,
      'ja': `${SITE_URL}/ja`,
      'x-default': SITE_URL,
    },
  },
}

// JSON-LD structured data for the organization
const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'NPLatform',
  url: SITE_URL,
  logo: `${SITE_URL}/logo.png`,
  description:
    '국내 최초 AI 기반 NPL(부실채권) 투자 분석 및 거래 플랫폼. 전국 NPL 매물 검색, AI 등급 평가, 수익률 시뮬레이션.',
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer service',
    email: 'support@nplatform.co.kr',
    availableLanguage: ['Korean', 'English', 'Japanese'],
  },
  sameAs: [],
}

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'NPLatform',
  url: SITE_URL,
  description: 'AI 기반 NPL 투자 분석 및 거래 플랫폼',
  inLanguage: ['ko', 'en', 'ja'],
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${SITE_URL}/market/search?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Read the nonce generated by middleware for CSP compliance
  const nonce = (await headers()).get('x-nonce') ?? undefined

  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        {/* hreflang for multi-language SEO */}
        <link rel="alternate" hrefLang="ko" href={SITE_URL} />
        <link rel="alternate" hrefLang="en" href={`${SITE_URL}/en`} />
        <link rel="alternate" hrefLang="ja" href={`${SITE_URL}/ja`} />
        <link rel="alternate" hrefLang="x-default" href={SITE_URL} />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#1B3A5C" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="NPLatform" />
        <link rel="apple-touch-icon" href="/favicon.png" />
        <script
          nonce={nonce}
          suppressHydrationWarning
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          nonce={nonce}
          suppressHydrationWarning
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        {/* Anti-FOUC: 라이트 기본, 사용자가 명시적으로 선택한 'dark'일 때만 클래스 적용 */}
        <script suppressHydrationWarning dangerouslySetInnerHTML={{ __html: `
          (function(){
            try {
              var s = localStorage.getItem('nplatform-theme');
              var t = s ? s.replace(/"/g,'') : 'light';
              if (t === 'dark') {
                document.documentElement.classList.add('dark');
              } else {
                document.documentElement.classList.remove('dark');
              }
            } catch(e) {
              // localStorage 실패 시 라이트 기본
            }
          })();
        `}} />
        <script nonce={nonce} suppressHydrationWarning dangerouslySetInnerHTML={{ __html: `
          if ('serviceWorker' in navigator && location.hostname !== 'localhost') {
            window.addEventListener('load', function() {
              navigator.serviceWorker.register('/sw.js');
            });
          }
        `}} />
      </head>
      <body className={`${pretendard.variable} ${pretendard.className}`}>
        {/* OfflineBanner and SkipLinks removed to fix webpack RSC error */}
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          storageKey="nplatform-theme"
          disableTransitionOnChange={false}
        >
          <QueryProvider>
            <AuthProvider>
              <AutoTranslateProvider />
              <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[9999] focus:px-4 focus:py-2 focus:bg-[#1B3A5C] focus:text-white focus:rounded-md">본문으로 건너뛰기</a>
              <main id="main-content" role="main">
                {children}
              </main>
              <div aria-live="polite" aria-atomic="true">
                <Toaster
                  position="top-right"
                  richColors
                  expand={false}
                  closeButton
                  toastOptions={{
                    style: {
                      fontFamily: 'var(--font-pretendard)',
                      fontSize: '0.875rem',
                      fontWeight: '500',
                      borderRadius: '12px',
                      boxShadow: '0 8px 32px rgba(13,31,56,0.14), 0 2px 8px rgba(13,31,56,0.08)',
                    },
                    classNames: {
                      toast: 'border border-[var(--color-border-subtle)] bg-[var(--color-surface-elevated)] text-[var(--color-text-primary)]',
                      success: '!bg-emerald-950 !text-emerald-300 !border-emerald-800',
                      error: '!bg-red-950 !text-red-300 !border-red-900',
                      warning: '!bg-amber-950 !text-amber-300 !border-amber-800',
                      info: '!bg-blue-950 !text-blue-300 !border-blue-800',
                    },
                  }}
                />
              </div>
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  )
}
