export interface APIIntegration {
  id: string
  provider: string
  category: 'ai' | 'document' | 'payment' | 'data' | 'cache' | 'map' | 'auth' | 'notification' | 'builtin'
  name: string
  description: string
  status: 'connected' | 'disconnected' | 'testing' | 'error'
  isBuiltin: boolean
  config: Record<string, string>
  monthlyUsage: number
  lastTestedAt: string | null
  docsUrl: string
  /** 이 연동이 활성화될 때 적용되는 환경변수 이름 목록 (안내용) */
  envVars?: string[]
  /** 연동 없이 플랫폼이 동작하는지 여부 */
  required?: boolean
}

export const API_CATEGORIES = {
  ai: { label: 'AI API', icon: 'Brain' },
  document: { label: '문서 처리', icon: 'FileText' },
  payment: { label: '결제/PG', icon: 'CreditCard' },
  data: { label: '데이터 파이프라인', icon: 'Database' },
  cache: { label: '캐시/인프라', icon: 'Zap' },
  map: { label: '지도/위치', icon: 'Map' },
  auth: { label: '인증/보안', icon: 'Shield' },
  notification: { label: '알림/메시징', icon: 'Bell' },
  builtin: { label: '내장 기능', icon: 'Package' },
} as const

export type APICategoryKey = keyof typeof API_CATEGORIES

export const API_INTEGRATIONS: APIIntegration[] = [
  {
    id: 'anthropic',
    provider: 'anthropic',
    category: 'ai',
    name: 'Anthropic Claude API',
    description: 'NPL 분석, AI 검수, 자연어 검색, 실사 리포트 생성에 사용',
    status: 'connected',
    isBuiltin: false,
    config: { model: 'claude-sonnet-4-20250514' },
    monthlyUsage: 1234,
    lastTestedAt: '2026-03-20T10:00:00Z',
    docsUrl: 'https://docs.anthropic.com',
  },
  {
    id: 'openai',
    provider: 'openai',
    category: 'ai',
    name: 'OpenAI GPT API',
    description: '대안 AI 엔진 (Claude 장애 시 폴백)',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://platform.openai.com/docs',
  },
  {
    id: 'google-vertex',
    provider: 'google',
    category: 'ai',
    name: 'Google Vertex AI',
    description: 'Google AI 모델 연동 (Gemini)',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://cloud.google.com/vertex-ai',
  },
  {
    id: 'google-documentai',
    provider: 'google',
    category: 'document',
    name: 'Google DocumentAI',
    description: 'OCR 문서 인식 — 엑셀/PDF/이미지에서 텍스트 추출',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://cloud.google.com/document-ai',
  },
  {
    id: 'jspdf',
    provider: 'builtin',
    category: 'document',
    name: 'PDF 생성 (jsPDF)',
    description: '계약서, 실사 리포트, 청구서 PDF 자동 생성',
    status: 'connected',
    isBuiltin: true,
    config: {},
    monthlyUsage: 456,
    lastTestedAt: '2026-03-20T10:00:00Z',
    docsUrl: '',
  },
  {
    id: 'docx',
    provider: 'builtin',
    category: 'document',
    name: 'Word 문서 생성 (DOCX)',
    description: '계약서 DOCX 템플릿 생성',
    status: 'connected',
    isBuiltin: true,
    config: {},
    monthlyUsage: 123,
    lastTestedAt: '2026-03-20T10:00:00Z',
    docsUrl: '',
  },
  // ── 데이터 파이프라인 ──────────────────────────────────────
  {
    id: 'molit',
    provider: 'molit',
    category: 'data',
    name: '국토교통부 실거래가 API',
    description: '아파트·오피스텔·상가·토지 실거래가 공공데이터. 일별 자동 수집으로 NBI 지수 및 시세 데이터 갱신.',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://www.data.go.kr/data/15058747/openapi.do',
    envVars: ['MOLIT_API_KEY'],
    required: true,
  },
  {
    id: 'onbid',
    provider: 'onbid',
    category: 'data',
    name: '온비드 공공자산 경매 API',
    description: '한국자산관리공사(KAMCO) 공매·경매 데이터. 낙찰가율 지수(NBI) 및 ML 학습 데이터 수집.',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://www.onbid.co.kr/op/ctr/openapiManage/selectOpenApiManage.do',
    envVars: ['ONBID_API_KEY'],
    required: true,
  },
  {
    id: 'cron-secret',
    provider: 'vercel-cron',
    category: 'data',
    name: 'Vercel Cron 시크릿',
    description: '데이터 파이프라인 자동 실행 인증 시크릿. 무단 파이프라인 트리거를 방지합니다.',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://vercel.com/docs/cron-jobs',
    envVars: ['CRON_SECRET'],
  },
  // ── 캐시/인프라 ────────────────────────────────────────────
  {
    id: 'upstash-redis',
    provider: 'upstash',
    category: 'cache',
    name: 'Upstash Redis',
    description: 'NBI 지수·분석 결과·AI 응답 Redis 캐싱. 미연동 시 인메모리 폴백(재시작 시 소실).',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://upstash.com/docs/redis/overall/getstarted',
    envVars: ['UPSTASH_REDIS_REST_URL', 'UPSTASH_REDIS_REST_TOKEN'],
  },
  // ── 결제 ──────────────────────────────────────────────────
  {
    id: 'portone',
    provider: 'portone',
    category: 'payment',
    name: 'PortOne (포트원) V2',
    description: '크레딧 구매·구독 결제·환불 처리. 카드, 계좌이체, 카카오페이, 네이버페이 지원.',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://developers.portone.io/docs/ko/v2-payment/',
    envVars: ['PORTONE_STORE_ID', 'PORTONE_CHANNEL_KEY', 'PORTONE_API_SECRET', 'PORTONE_WEBHOOK_SECRET'],
    required: true,
  },
  {
    id: 'toss-payments',
    provider: 'toss',
    category: 'payment',
    name: '토스페이먼츠 (레거시)',
    description: '구독 결제, 크레딧 구매, 거래 수수료 결제',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://docs.tosspayments.com',
  },
  {
    id: 'inicis',
    provider: 'inicis',
    category: 'payment',
    name: '이니시스',
    description: '대안 PG사 (카드/계좌이체)',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://manual.inicis.com',
  },
  {
    id: 'kakaopay',
    provider: 'kakao',
    category: 'payment',
    name: '카카오페이',
    description: '간편결제',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://developers.kakao.com/docs/latest/ko/kakaopay',
  },
  {
    id: 'kakao-map',
    provider: 'kakao',
    category: 'map',
    name: '카카오맵 API',
    description: '매물 지도 표시, 위치 검색',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://apis.map.kakao.com',
  },
  {
    id: 'naver-map',
    provider: 'naver',
    category: 'map',
    name: '네이버 지도 API',
    description: '대안 지도 서비스',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://navermaps.github.io/maps.js.ncp',
  },
  {
    id: 'supabase',
    provider: 'supabase',
    category: 'auth',
    name: 'Supabase',
    description: '데이터베이스, 인증, 실시간, 스토리지',
    status: 'connected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 52340,
    lastTestedAt: '2026-03-21T00:00:00Z',
    docsUrl: 'https://supabase.com/docs',
  },
  {
    id: 'nice-auth',
    provider: 'nice',
    category: 'auth',
    name: 'NICE 본인인증',
    description: '실명인증, 본인확인',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://www.niceapi.co.kr',
  },
  {
    id: 'kakao-alimtalk',
    provider: 'kakao',
    category: 'notification',
    name: '카카오 알림톡',
    description: '거래 알림, 승인 알림, 마케팅 메시지',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: 'https://developers.kakao.com/docs/latest/ko/message',
  },
  {
    id: 'smtp',
    provider: 'smtp',
    category: 'notification',
    name: '이메일 (SMTP)',
    description: '이메일 알림, 청구서 발송',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: '',
  },
  {
    id: 'web-push',
    provider: 'web-push',
    category: 'notification',
    name: 'Web Push (VAPID)',
    description: '브라우저 푸시 알림',
    status: 'disconnected',
    isBuiltin: false,
    config: {},
    monthlyUsage: 0,
    lastTestedAt: null,
    docsUrl: '',
  },
  {
    id: 'excel-export',
    provider: 'builtin',
    category: 'builtin',
    name: '엑셀 내보내기',
    description: '매물, 거래, 수익 데이터 CSV/엑셀 다운로드',
    status: 'connected',
    isBuiltin: true,
    config: {},
    monthlyUsage: 89,
    lastTestedAt: '2026-03-20T10:00:00Z',
    docsUrl: '',
  },
  {
    id: 'watermark',
    provider: 'builtin',
    category: 'builtin',
    name: 'PDF 워터마크',
    description: '문서 다운로드 시 사용자 워터마크 자동 삽입',
    status: 'connected',
    isBuiltin: true,
    config: {},
    monthlyUsage: 234,
    lastTestedAt: '2026-03-20T10:00:00Z',
    docsUrl: '',
  },
  {
    id: 'audit-log',
    provider: 'builtin',
    category: 'builtin',
    name: '감사 로그',
    description: '모든 데이터 접근/변경 자동 기록',
    status: 'connected',
    isBuiltin: true,
    config: {},
    monthlyUsage: 15670,
    lastTestedAt: '2026-03-21T00:00:00Z',
    docsUrl: '',
  },
]

/** Field definitions for each API provider's config form */
export const API_CONFIG_FIELDS: Record<string, { key: string; label: string; type: 'text' | 'password' | 'select'; placeholder?: string; hint?: string; options?: string[] }[]> = {
  // ── 데이터 파이프라인 ──────────────────────────────────────
  molit: [
    {
      key: 'api_key',
      label: '공공데이터포털 인증키',
      type: 'password',
      placeholder: 'URL 인코딩된 인증키 붙여넣기',
      hint: '공공데이터포털(data.go.kr) → 마이페이지 → 인증키 복사. 아파트매매 실거래 API 신청 필요.',
    },
  ],
  onbid: [
    {
      key: 'api_key',
      label: '온비드 API Key',
      type: 'password',
      placeholder: 'onbid.co.kr API 키',
      hint: '온비드(onbid.co.kr) → 오픈API 관리 → API 키 발급. 부동산 공매 데이터 수집용.',
    },
  ],
  'vercel-cron': [
    {
      key: 'cron_secret',
      label: 'Cron 시크릿',
      type: 'password',
      placeholder: '영숫자 32자 이상 랜덤 문자열',
      hint: '무단 파이프라인 트리거 방지용. openssl rand -base64 32 로 생성 권장.',
    },
  ],
  upstash: [
    {
      key: 'rest_url',
      label: 'Redis REST URL',
      type: 'text',
      placeholder: 'https://xxx.upstash.io',
      hint: 'Upstash 콘솔 → Database → REST API → UPSTASH_REDIS_REST_URL',
    },
    {
      key: 'rest_token',
      label: 'Redis REST Token',
      type: 'password',
      placeholder: 'AXxx...',
      hint: 'Upstash 콘솔 → Database → REST API → UPSTASH_REDIS_REST_TOKEN',
    },
  ],
  portone: [
    {
      key: 'store_id',
      label: 'Store ID',
      type: 'text',
      placeholder: 'store-xxxxxxxx',
      hint: '포트원 콘솔 → 스토어 ID',
    },
    {
      key: 'channel_key',
      label: 'Channel Key',
      type: 'password',
      placeholder: 'channel-key-xxxxxxxx',
      hint: '포트원 콘솔 → 결제 연동 → 채널키 (결제 수단별)',
    },
    {
      key: 'api_secret',
      label: 'V2 API Secret',
      type: 'password',
      placeholder: 'V2 API 시크릿',
      hint: '포트원 콘솔 → 개발자 → V2 API Secret. 서버사이드 결제 검증에 사용.',
    },
    {
      key: 'webhook_secret',
      label: 'Webhook Secret',
      type: 'password',
      placeholder: 'Webhook 서명 검증 시크릿',
      hint: '포트원 콘솔 → 개발자 → Webhook 시크릿. 결제 완료 알림 서명 검증용.',
    },
    {
      key: 'mode',
      label: '환경',
      type: 'select',
      options: ['sandbox', 'production'],
      hint: '연동 전에는 sandbox로 테스트하세요.',
    },
  ],
  anthropic: [
    { key: 'api_key', label: 'API Key', type: 'password' },
    { key: 'model', label: 'Model', type: 'select', options: ['claude-sonnet-4-20250514', 'claude-opus-4-20250514', 'claude-haiku-4-20250514'] },
  ],
  openai: [
    { key: 'api_key', label: 'API Key', type: 'password' },
    { key: 'model', label: 'Model', type: 'select', options: ['gpt-4o', 'gpt-4o-mini', 'o1'] },
  ],
  'google-vertex': [
    { key: 'project_id', label: 'Project ID', type: 'text' },
    { key: 'credentials', label: 'Service Account JSON', type: 'password' },
  ],
  'google-documentai': [
    { key: 'project_id', label: 'Project ID', type: 'text' },
    { key: 'processor_id', label: 'Processor ID', type: 'text' },
    { key: 'credentials', label: 'Service Account JSON', type: 'password' },
  ],
  'toss-payments': [
    { key: 'client_key', label: 'Client Key', type: 'password' },
    { key: 'secret_key', label: 'Secret Key', type: 'password' },
    { key: 'mode', label: '환경', type: 'select', options: ['test', 'production'] },
  ],
  inicis: [
    { key: 'merchant_id', label: 'Merchant ID', type: 'text' },
    { key: 'sign_key', label: 'Sign Key', type: 'password' },
  ],
  kakaopay: [
    { key: 'admin_key', label: 'Admin Key', type: 'password' },
  ],
  'kakao-map': [
    { key: 'javascript_key', label: 'JavaScript Key', type: 'password' },
    { key: 'rest_key', label: 'REST API Key', type: 'password' },
  ],
  'naver-map': [
    { key: 'client_id', label: 'Client ID', type: 'text' },
    { key: 'client_secret', label: 'Client Secret', type: 'password' },
  ],
  supabase: [
    { key: 'url', label: 'Project URL', type: 'text' },
    { key: 'anon_key', label: 'Anon Key', type: 'password' },
    { key: 'service_role_key', label: 'Service Role Key', type: 'password' },
  ],
  'nice-auth': [
    { key: 'site_code', label: 'Site Code', type: 'text' },
    { key: 'site_password', label: 'Site Password', type: 'password' },
  ],
  'kakao-alimtalk': [
    { key: 'sender_key', label: 'Sender Key', type: 'password' },
    { key: 'template_codes', label: 'Template Codes (쉼표 구분)', type: 'text' },
  ],
  smtp: [
    { key: 'host', label: 'SMTP Host', type: 'text' },
    { key: 'port', label: 'Port', type: 'text' },
    { key: 'user', label: 'Username', type: 'text' },
    { key: 'password', label: 'Password', type: 'password' },
  ],
  'web-push': [
    { key: 'public_key', label: 'VAPID Public Key', type: 'text' },
    { key: 'private_key', label: 'VAPID Private Key', type: 'password' },
  ],
}
