// npl-table-maps.ts
// Category-to-field and field-to-unit mappings from marketplace source
// Auto-generated — do not edit manually

/** Maps each category to its sub-field label → DB field path */
export const subToFieldMap: Record<string, Record<string, string>> = {
    개요: {
        등록일: 'up_at',
        상태: 'status',
        '상태 (기준일)': 'base_date',
        채권기관: 'creditor_institution',
        담당자명: '',
        '담당자 연락처': '',
        채무자유형: 'is_corporation',
        '담보물 유형': 'type',
    },
    '담보물 정보': {
        지역: 'address_info.sido',
        // 시군구: 'address_info.gugun',
        // 읍면동: 'address_info.dong',
        '용도 지역': 'zoning',
        '담보물 주소': 'address',
        '호실 수': 'ho_num',
        '사용 승인일': 'approval_date',
        '대지면적 ㎡': 'area',
        '전용면적 ㎡': 'building_area',
        대지평수: 'area_pyeong',
        전용평수: 'building_area_pyeong',
    },
    '채권 수익성': {
        '원금대비 총 채권액 %': 'claim_profitability',
        //'원금대비 청구금액 %': 'claim_to_principal_ratio',
        '연체금리 수준 %': 'overdue_interest_rate',
    },
    '채권 상세 정보': {
        '총 채권액': 'total_claim_amount',
        '대출잔액(미상환원리금)': 'loan_balance',
        대출원금: 'loan_principal',
        '설정금액(채권최고액)': 'setting_amount',
    },
    이자: {
        정상이자: 'normal_interest',
        연체이자: 'overdue_interest',
        미수이자: 'unpaid_interest',
        가지급비용: 'prepaid_cost',
        대출기간: 'loan_period',
        담보인정비율: 'ltv_ratio',
        대출금리: 'loan_interest_rate',
        연체금리: 'overdue_interest_rate',
        원금연체시작일: 'overdue_start_date',
    },
    권리관계: {
        채권보전방식: 'claim_preservation_method',
        '1순위': 'first_rank',
        '2순위': 'second_rank',
        수익권금액: 'profit_right_amount',
    },
    가치평가: {
        '감정가(법사가)': 'appraisal_value',
        '토지 평단가': 'appraisal_value_land_pyeong',
        '전용 평단가': 'appraisal_value_building_pyeong',
        // '공시가격 구간': '',
        공시가격: 'official_price',
        // '토지 공시지가': 'official_price_land',
        '토지 공시지가(평)': 'official_price_land',
        '토지 공시지가(㎡)': 'official_price_land',
        '건물 공시가격': 'official_price_building',
        // 'AI 추정가': '',
        // 'AI 토지평단가': '',
        // 'AI 전용평단가': '',
        // '1년 실거래 평균 (상가)': '',
        // '1년 실거래 평균 (오피스텔)': '',
        // '1년 실거래 평균 (지산)': '',
        // '1년 실거래 평균 (빌라)': '',
        // '1년 실거래 평균 (빌딩)': '',
        // '1년 실거래 평균 (아파트)': '',
        // '현재 매물 최저가 (아파트)': '',
        // '현재 매물 최저가 (빌라)': '',
        '1년 실거래가 평균': 'realdeal_avg',
        '1년 실거래가 평균(㎡)': 'realdeal_avg_area',
        '1년 실거래가 평균(평)': 'realdeal_avg_pyeong',
        '현재 네이버 매물 평균가': '',
        '3개월 네이버 매물 최저가': 'sales_min_price',
        'KB 매매시세 상한': '',
        'KB 매매시세 평균': '',
        'KB 매매시세 하한': '',
        'KB 전세시세 평균': '',
        'KB 월세 보증금': '',
        'KB 월세': '',
        '이전 최고가': '',
        '최고가 날짜': '',
        // '최근 실거래가': '',
        // '최근 실거래 날짜': '',
        '6개월 이내 거래건수': '',
        급매: '',
        '최저시세 대비 가격': '',
        '최저시세 대비 비율': '',
        갭차이: '',
        '고점 대비 가격': '',
        '고점 대비 하락율': '',
        '최근 실거래 차이가': '',
        '최근 실거래 차이비율': '',
        '실거래 평균 차이': '',
    },

    '임차인 현황': {
        선순위임차인내역: 'priority_lessee_details',
        보증금: 'deposit',
        월세: 'monthly_rent',
        공실여부: 'vacancy_status',
    },
    매각조건: {
        '최저 매각가': 'min_sale_price',
        '매각 조건': 'sale_conditions',
        계약금: 'contract_deposit',
        잔금일: 'balance_date',
        '제안 매각가': 'proposed_sale_price',
    },
    '경공매 및 기타': { '경공매 진행': 'caseno', 특이사항: 'etc' },
};

/** Maps sub-field labels to their display units */
export const subToUnitMap: Record<string, string> = {
    공시가격: '원',
    '대지면적 ㎡': '㎡',
    '전용면적 ㎡': '㎡',
    대지평수: '평',
    전용평수: '평',
    '총 채권액': '원',
    '대출잔액(미상환원리금)': '원',
    대출원금: '원',
    '설정금액(채권최고액)': '원',
    정상이자: '원',
    연체이자: '원',
    미수이자: '원',
    가지급비용: '원',
    담보인정비율: '%',
    '감정가(법사가)': '원',
    '토지 평단가': '원/평',
    '전용 평단가': '원/평',
    // 'AI 추정가': '원',
    // 'AI 토지평단가': '원/평',
    // 'AI 전용평단가': '원/평',
    '1년 실거래가 평균': '원',
    '1년 실거래가 평균(㎡)': '원/㎡',
    '1년 실거래가 평균(평)': '원/평',
    '현재 네이버 매물 평균가': '원',
    '3개월 네이버 매물 최저가': '원',
    '1년 실거래 평균 (상가)': '원',
    '1년 실거래 평균 (오피스텔)': '원',
    '1년 실거래 평균 (지산)': '원',
    '1년 실거래 평균 (빌라)': '원',
    '1년 실거래 평균 (빌딩)': '원',
    '1년 실거래 평균 (아파트)': '원',
    '현재 매물 최저가 (아파트)': '원',
    '현재 매물 최저가 (빌라)': '원',
    'KB 매매시세 상한': '원',
    'KB 매매시세 평균': '원',
    'KB 매매시세 하한': '원',
    'KB 전세시세 평균': '원',
    'KB 월세 보증금': '원',
    'KB 월세': '원',
    '이전 최고가': '원',
    '최근 실거래가': '원',
    '6개월 이내 거래건수': '건',
    급매: '원',
    // '최저시세 대비 가격': '',
    // '최저시세 대비 비율': '',
    갭차이: '원',
    // '고점 대비 가격': '',
    // '고점 대비 하락율': '',
    // '최근 실거래 차이가': '',
    // '최근 실거래 차이비율': '',
    // '실거래 평균 차이': '',
    '토지 공시지가(평)': '원/평',
    '토지 공시지가(㎡)': '원/㎡',
    '건물 공시가격': '원',
    수익권금액: '원',
    보증금: '원',
    월세: '원',
    '최저 매각가': '원',
    '제안 매각가': '원',
};

/** Sortable columns per category */
export const sortableColumns: Record<string, string[]> = {
    개요: ['등록일', '상태 (기준일)'],
    '담보물 정보': ['호실 수', '사용 승인일', '대지면적 ㎡', '전용면적 ㎡', '대지평수', '전용평수'],
    '채권 수익성': [
        '원금대비 총 채권액 %',
        //'원금대비 청구금액 %',
        '연체금리 수준 %',
    ],
    '채권 상세 정보': ['총 채권액', '대출잔액(미상환원리금)', '대출원금', '설정금액(채권최고액)'],
    이자: [
        '정상이자',
        '연체이자',
        '미수이자',
        '가지급비용',
        '대출기간',
        '담보인정비율',
        '대출금리',
        '연체금리',
        '원금연체시작일',
    ],
    권리관계: ['수익권금액'],
    가치평가: [
        '감정가(법사가)',
        '토지 평단가',
        '전용 평단가',
        // '공시가격',
        '토지 공시지가(평)',
        '토지 공시지가(㎡)',
        '건물 공시가격',
        '1년 실거래가 평균',
        '1년 실거래가 평균(㎡)',
        '1년 실거래가 평균(평)',
        // '현재 네이버 매물 평균가',
        '3개월 네이버 매물 최저가',
        // 'AI 추정가',
        // 'AI 토지평단가',
        // 'AI 전용평단가',
        // '1년 실거래 평균 (상가)',
        // '1년 실거래 평균 (오피스텔)',
        // '1년 실거래 평균 (지산)',
        // '1년 실거래 평균 (빌라)',
        // '1년 실거래 평균 (빌딩)',
        // '1년 실거래 평균 (아파트)',
        // '현재 매물 최저가 (아파트)',
        // '현재 매물 최저가 (빌라)',
        'KB 매매시세 상한',
        'KB 매매시세 평균',
        'KB 매매시세 하한',
        'KB 전세시세 평균',
        'KB 월세 보증금',
        'KB 월세',
        '이전 최고가',
        '최고가 날짜',
        // '최근 실거래가',
        // '최근 실거래 날짜',
        '6개월 이내 거래건수',
        '급매',
        '최저시세 대비 가격',
        '최저시세 대비 비율',
        '갭차이',
        '고점 대비 가격',
        '고점 대비 하락율',
        '최근 실거래 차이가',
        '최근 실거래 차이비율',
        '실거래 평균 차이',
    ],
    '임차인 현황': ['보증금', '월세'],
    매각조건: ['최저 매각가', '제안 매각가'],
};

/** Returns data source attribution text for a given sub-field */
export const getSourceText = (sub: string): string => {
    const 국토부 = [
        '1년 실거래 평균 (상가)',
        '1년 실거래 평균 (오피스텔)',
        '1년 실거래 평균 (지산)',
        '1년 실거래 평균 (빌라)',
    ];

    const 네이버 = [
        '1년 실거래 평균 (빌딩)',
        '1년 실거래 평균 (아파트)',
        '현재 매물 최저가 (아파트)',
        '현재 매물 최저가 (빌라)',
    ];

    const KB = [
        'KB 매매시세 상한',
        'KB 매매시세 평균',
        'KB 매매시세 하한',
        'KB 전세시세 평균',
        'KB 월세 보증금',
        'KB 월세',
    ];

    if (국토부.includes(sub)) return '출처: 국토부 실거래가';
    if (네이버.includes(sub)) return '출처: 네이버 부동산';
    if (KB.includes(sub)) return '출처: KB 부동산';

    return '';
};

/** The list of major categories (derived from subToFieldMap keys) */
export const categories: string[] = Object.keys(subToFieldMap);

/** Mapping of each category to its sub-field labels */
export const subcategories: Record<string, string[]> = Object.fromEntries(
    Object.entries(subToFieldMap).map(([cat, fields]) => [cat, Object.keys(fields)])
);
